# Generated by Django 2.2.7 on 2019-11-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191122_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zhiwu',
            new_name='zhihu',
        ),
    ]
