# Generated by Django 2.2.7 on 2019-11-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191122_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pictrure',
            new_name='picture',
        ),
    ]
